import type { Chamber, Slot, PatientAppointment, DoctorProfile } from './types';

export const initialDoctorProfile: DoctorProfile = {
  name: 'ডা. হরিপদ',
  englishName: 'Dr. Haripada',
  title: 'হৃদরোগ, উচ্চ রক্তচাপ ও কার্ডিওলজি বিশেষজ্ঞ এবং সার্জন',
  degrees: 'এমবিবিএস (ডিএমসি), বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন), এমডি (কার্ডিওলজি)',
  designation: 'সিনিয়র কার্ডিওলজিস্ট ও হৃদরোগ সার্জন, রংপুর',
  experience: '১৫+ বছর',
  helpline: '০১৭৫২-১১২২৩৩',
  bio: 'উত্তরবঙ্গের অন্যতম শীর্ষস্থানীয় হৃদরোগ ও কার্ডিওলজি বিশেষজ্ঞ। জটিল হৃদরোগ, হার্ট ব্লক, ইকোকার্ডিওগ্রাফি এবং ইন্টারভেনশনাল কার্ডিওলজি সেবায় দীর্ঘ ১৫ বছরের সফল অভিজ্ঞতাসম্পন্ন।',
};

export const initialChambers: Chamber[] = [
  {
    id: 'chamber_central',
    name: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল ও হার্ট সেন্টার',
    location: 'জেল রোড, ধাপ মোড়, রংপুর',
    contactNumber: '০১৭৫২-১১২২৩৩',
    visitingDays: 'শনিবার - বৃহস্পতিবার',
    visitingHours: 'বিকাল ৪:০০ টা – সন্ধ্যা ৬:৩০ টা',
    consultationFee: '৳ ৮০০',
    followUpFee: '৳ ৫০০',
    isActive: true,
  },
  {
    id: 'chamber_popular',
    name: 'পপুলার ডায়াগনস্টিক সেন্টার',
    location: 'ধাপ, জেল রোড ক্রসিং, রংপুর',
    contactNumber: '০১৭৯৯-৪৪৭৭৮৮',
    visitingDays: 'শনিবার - বৃহস্পতিবার',
    visitingHours: 'সন্ধ্যা ৭:০০ টা – রাত ৯:৩০ টা',
    consultationFee: '৳ ৮০০',
    followUpFee: '৳ ৫০০',
    isActive: true,
  },
];

export const initialSlots: Slot[] = [
  {
    id: 'slot_1',
    chamberId: 'chamber_central',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    timeRange: 'বিকাল ৪:০০ – ৫:০০',
    defaultLimit: 20,
    isActive: true,
  },
  {
    id: 'slot_2',
    chamberId: 'chamber_central',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    timeRange: 'বিকাল ৫:০০ – ৬:০০',
    defaultLimit: 20,
    isActive: true,
  },
  {
    id: 'slot_3',
    chamberId: 'chamber_popular',
    chamberName: 'পপুলার ডায়াগনস্টিক সেন্টার',
    timeRange: 'সন্ধ্যা ৭:০০ – ৮:০০',
    defaultLimit: 25,
    isActive: true,
  },
  {
    id: 'slot_4',
    chamberId: 'chamber_popular',
    chamberName: 'পপুলার ডায়াগনস্টিক সেন্টার',
    timeRange: 'রাত ৮:০০ – ৯:০০',
    defaultLimit: 25,
    isActive: true,
  },
];

const now = new Date();
const todayKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;

export const initialAppointments: PatientAppointment[] = [
  {
    id: 'apt_1',
    serialNumber: 1,
    tokenCode: `HP-${todayKey.replace(/-/g, '')}-001`,
    patientName: 'মো. আব্দুল কাদের',
    patientPhone: '০১৭২২-৯৮৭৬৫৪',
    patientAge: 58,
    patientGender: 'পুরুষ',
    problemDescription: 'বুকে চিনচিন ব্যথা ও ভারী লাগা',
    dateKey: todayKey,
    slotId: 'slot_1',
    slotTime: 'বিকাল ৪:০০ – ৫:০০',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    chamberLocation: 'ধাপ, রংপুর',
    bookedAt: new Date(now.getTime() - 1000 * 60 * 125 - 432).toISOString(),
    status: 'completed',
  },
  {
    id: 'apt_2',
    serialNumber: 2,
    tokenCode: `HP-${todayKey.replace(/-/g, '')}-002`,
    patientName: 'বেগম রাজিয়া সুলতানা',
    patientPhone: '০১৮১৯-৪৫৫৬৬৭',
    patientAge: 49,
    patientGender: 'মহিলা',
    problemDescription: 'উচ্চ রক্তচাপ ও হঠাৎ বুক ধড়ফড়',
    dateKey: todayKey,
    slotId: 'slot_1',
    slotTime: 'বিকাল ৪:০০ – ৫:০০',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    chamberLocation: 'ধাপ, রংপুর',
    bookedAt: new Date(now.getTime() - 1000 * 60 * 110 - 120).toISOString(),
    status: 'completed',
  },
  {
    id: 'apt_3',
    serialNumber: 3,
    tokenCode: `HP-${todayKey.replace(/-/g, '')}-003`,
    patientName: 'সুশীল কুমার রায়',
    patientPhone: '০১৭৫১-৩৩৪২৫৬',
    patientAge: 62,
    patientGender: 'পুরুষ',
    problemDescription: 'এনজিওগ্রাম পরবর্তী নিয়মিত ফলোআপ চেকআপ',
    dateKey: todayKey,
    slotId: 'slot_1',
    slotTime: 'বিকাল ৪:০০ – ৫:০০',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    chamberLocation: 'ধাপ, রংপুর',
    bookedAt: new Date(now.getTime() - 1000 * 60 * 95 - 670).toISOString(),
    status: 'in_chamber',
  },
  {
    id: 'apt_4',
    serialNumber: 4,
    tokenCode: `HP-${todayKey.replace(/-/g, '')}-004`,
    patientName: 'আফসানা মিমি',
    patientPhone: '০১৬২৪-১১২২৩৩',
    patientAge: 35,
    patientGender: 'মহিলা',
    problemDescription: 'শ্বাসকষ্ট ও সিঁড়ি বেয়ে উঠতে দুর্বলতা',
    dateKey: todayKey,
    slotId: 'slot_1',
    slotTime: 'বিকাল ৪:০০ – ৫:০০',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    chamberLocation: 'ধাপ, রংপুর',
    bookedAt: new Date(now.getTime() - 1000 * 60 * 80 - 890).toISOString(),
    status: 'waiting',
  },
  {
    id: 'apt_5',
    serialNumber: 5,
    tokenCode: `HP-${todayKey.replace(/-/g, '')}-005`,
    patientName: 'তানভীর হাসান',
    patientPhone: '০১৭৭৮-০০৯৯৮৮',
    patientAge: 42,
    patientGender: 'পুরুষ',
    problemDescription: 'ইকো ও ইসিজি টেস্টের রিপোর্ট বিশ্লেষণ',
    dateKey: todayKey,
    slotId: 'slot_1',
    slotTime: 'বিকাল ৪:০০ – ৫:০০',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    chamberLocation: 'ধাপ, রংপুর',
    bookedAt: new Date(now.getTime() - 1000 * 60 * 65 - 340).toISOString(),
    status: 'waiting',
  },
  {
    id: 'apt_6',
    serialNumber: 6,
    tokenCode: `HP-${todayKey.replace(/-/g, '')}-006`,
    patientName: 'নুরজাহান বেগম',
    patientPhone: '০১৭৩৩-৪৪০৩৯২',
    patientAge: 53,
    patientGender: 'মহিলা',
    problemDescription: 'কোলেস্টেরল বেশি ও বুক জ্বালাপোড়া',
    dateKey: todayKey,
    slotId: 'slot_1',
    slotTime: 'বিকাল ৪:০০ – ৫:০০',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    chamberLocation: 'ধাপ, রংপুর',
    bookedAt: new Date(now.getTime() - 1000 * 60 * 45 - 210).toISOString(),
    status: 'waiting',
  },
  {
    id: 'apt_7',
    serialNumber: 7,
    tokenCode: `HP-${todayKey.replace(/-/g, '')}-007`,
    patientName: 'দেবাশীষ চক্রবর্তী',
    patientPhone: '০১৮১৬-৭৭৮৮৯৯',
    patientAge: 65,
    patientGender: 'পুরুষ',
    problemDescription: 'পেমেকার লাগানো আছে, রুটিন চেকআপ',
    dateKey: todayKey,
    slotId: 'slot_1',
    slotTime: 'বিকাল ৪:০০ – ৫:০০',
    chamberName: 'সেন্ট্রাল স্পেশালাইজড হাসপাতাল',
    chamberLocation: 'ধাপ, রংপুর',
    bookedAt: new Date(now.getTime() - 1000 * 60 * 20 - 750).toISOString(),
    status: 'waiting',
  },
];
